#!/bin/bash
FILE="$1"

# If the file change something
# The command: sh auto.sh will be call

LAST=`ls -l "$FILE"`
while true; do
  sleep 1
  NEW=`ls -l "$FILE"`
  if [ "$NEW" != "$LAST" ]; then
    sh auto_read_and_run_sql_file.sh "$1"
    LAST="$NEW"
  fi
done
