# Using the command: brew bundle 
# for download the libraries
brew "bat"
brew "nvim"
brew "tmux"
brew "fish"
brew "fisher"
brew "peco"
brew "starship"
brew "htop"
brew "go"
brew "ruby"
brew "shellcheck"
brew "sqlite"
brew "sqls"
# Kubernetes
brew "kubernetes-cli"
# ...for configuring the Minikube cluster
brew "kubectl"
brew "netcat"

# Casks
cask "spotify"
cask "alacritty"
cask "numi"
